kind: Service
apiVersion: v1
metadata:
  name: artifacts
  labels:
    app: artifacts
spec:
  selector:
    name: artifacts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: grpc
  type: NodePort
